### ISSUE TITLE
Enhance the robustness of the sidecar of the WATCH method startup

### ISSUE THREAD

**Issue by OmegaVVeapon** [OmegaVVeapon/kopf-k8s-sidecar#21]
Looks like an error in reaching the k8s API caused the resource observer to not get created properly.

```
Setting USER environment variable to 472
[2021-06-01 12:04:40,102[] kopf.activities.star [INFO    [] Using the WATCH METHOD
[2021-06-01 12:04:40,103[] kopf.reactor.running [WARNING [] OS signals are ignored: running not in the main thread.
[2021-06-01 12:04:40,103[] kopf.activities.star [INFO    [] The default FOLDER to write files to is /tmp/dashboards
[2021-06-01 12:04:40,103[] kopf.activities.star [INFO    [] FOLDER_ANNOTATION not set. Defaulting to look for 'k8s-sidecar-target-directory'
[2021-06-01 12:04:40,103[] kopf.activities.star [INFO    [] Looking for resources with LABEL 'grafana_dashboard'
[2021-06-01 12:04:40,103[] kopf.activities.star [INFO    [] Monitoring configmap and secret resources for changes
[2021-06-01 12:04:40,103[] kopf.activities.star [INFO    [] Looking for resources in the entire cluster
[2021-06-01 12:04:40,103[] kopf.activities.star [INFO    [] Client watching requests using a timeout of 660 seconds
[2021-06-01 12:04:40,103[] kopf.activities.star [INFO    [] Server watching requests using a timeout of 600 seconds
[2021-06-01 12:04:40,104[] kopf.activities.star [INFO    [] Activity 'startup_tasks' succeeded.
[2021-06-01 12:04:40,104[] kopf.reactor.activit [INFO    [] Initial authentication has been initiated.
[2021-06-01 12:04:40,105[] kopf.activities.auth [INFO    [] Activity 'login_via_pykube' succeeded.
[2021-06-01 12:04:40,106[] kopf.reactor.activit [INFO    [] Initial authentication has finished.
[2021-06-01 12:04:40,293[] kopf.reactor.running [ERROR   [] Resource observer has failed: (None, None)
Traceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/kopf/clients/errors.py", line 133, in check_response
    response.raise_for_status()
  File "/.venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 503, message='Service Unavailable', url=URL('https://192.168.0.1:443/apis/external.metrics.k8s.io/v1beta1')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/kopf/utilities/aiotasks.py", line 69, in guard
    await coro
  File "/.venv/lib/python3.8/site-packages/kopf/reactor/observation.py", line 104, in resource_observer
    resources = await scanning.scan_resources(groups=group_filter)
  File "/.venv/lib/python3.8/site-packages/kopf/clients/auth.py", line 44, in wrapper
    return await fn(*args, **kwargs, context=context)
  File "/.venv/lib/python3.8/site-packages/kopf/clients/scanning.py", line 22, in scan_resources
    resources.update(await coro)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 619, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/.venv/lib/python3.8/site-packages/kopf/clients/scanning.py", line 72, in _read_new_apis
    resources.update(await coro)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 619, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/.venv/lib/python3.8/site-packages/kopf/clients/scanning.py", line 85, in _read_version
    rsp = await errors.parse_response(await context.session.get(url))
  File "/.venv/lib/python3.8/site-packages/kopf/clients/errors.py", line 144, in parse_response
    await check_response(response)
  File "/.venv/lib/python3.8/site-packages/kopf/clients/errors.py", line 135, in check_response
    raise cls(payload, status=response.status) from e
kopf.clients.errors.APIError: (None, None)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "sidecar.py", line 82, in kopf_thread
    loop.run_until_complete(kopf.operator(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/.venv/lib/python3.8/site-packages/kopf/reactor/running.py", line 118, in operator
    await run_tasks(operator_tasks, ignored=existing_tasks)
  File "/.venv/lib/python3.8/site-packages/kopf/reactor/running.py", line 355, in run_tasks
    await aiotasks.reraise(root_done | root_cancelled | hung_done | hung_cancelled)
  File "/.venv/lib/python3.8/site-packages/kopf/utilities/aiotasks.py", line 199, in reraise
    task.result()  # can raise the regular (non-cancellation) exceptions.
  File "/.venv/lib/python3.8/site-packages/kopf/clients/scanning.py", line 85, in _read_version
    rsp = await errors.parse_response(await context.session.get(url))
  File "/.venv/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 538, in connect
    raise ClientConnectionError("Connector is closed.")
aiohttp.client_exceptions.ClientConnectionError: Connector is closed.
```

This is a similar issue to https://github.com/OmegaVVeapon/kopf-k8s-sidecar/issues/20 where bad k8s API servers can cause unrecoverable issues during startup.

Luckily, it looks like once the operator is going, it can recover from issues like these by itself. 

Will still need to find a way to induce bad API connection issues to test for conditions like these that don't happen in healthy k8s clusters.

**Comment by OmegaVVeapon** [comment]
Got another variation of the same error:

```
Setting USER environment variable to 472
[2021-06-03 17:34:01,677] kopf.activities.star [INFO    ] Using the WATCH METHOD
[2021-06-03 17:34:01,678] kopf.reactor.running [WARNING ] OS signals are ignored: running not in the main thread.
[2021-06-03 17:34:01,678] kopf.activities.star [INFO    ] The default FOLDER to write files to is /tmp/dashboards
[2021-06-03 17:34:01,877] kopf.activities.star [INFO    ] FOLDER_ANNOTATION not set. Defaulting to look for 'k8s-sidecar-target-directory'
[2021-06-03 17:34:01,877] kopf.activities.star [INFO    ] Looking for resources with LABEL 'grafana_dashboard'
[2021-06-03 17:34:01,878] kopf.activities.star [INFO    ] Monitoring configmap and secret resources for changes
[2021-06-03 17:34:01,878] kopf.activities.star [INFO    ] Looking for resources in the entire cluster
[2021-06-03 17:34:01,878] kopf.activities.star [INFO    ] Client watching requests using a timeout of 660 seconds
[2021-06-03 17:34:01,878] kopf.activities.star [INFO    ] Server watching requests using a timeout of 600 seconds
[2021-06-03 17:34:01,879] kopf.activities.star [INFO    ] Activity 'startup_tasks' succeeded.
[2021-06-03 17:34:01,880] kopf.reactor.activit [INFO    ] Initial authentication has been initiated.
[2021-06-03 17:34:02,178] kopf.activities.auth [INFO    ] Activity 'login_via_pykube' succeeded.
[2021-06-03 17:34:02,178] kopf.reactor.activit [INFO    ] Initial authentication has finished.
[2021-06-03 17:34:15,719] kopf.reactor.running [ERROR   ] Resource observer has failed: Cannot connect to host 192.168.0.1:443 ssl:default [Connect call failed ('192.168.0.1', 443)]
Traceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.1', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/kopf/utilities/aiotasks.py", line 69, in guard
    await coro
  File "/.venv/lib/python3.8/site-packages/kopf/reactor/observation.py", line 104, in resource_observer
    resources = await scanning.scan_resources(groups=group_filter)
  File "/.venv/lib/python3.8/site-packages/kopf/clients/auth.py", line 44, in wrapper
    return await fn(*args, **kwargs, context=context)
  File "/.venv/lib/python3.8/site-packages/kopf/clients/scanning.py", line 22, in scan_resources
    resources.update(await coro)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 619, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/.venv/lib/python3.8/site-packages/kopf/clients/scanning.py", line 59, in _read_new_apis
    rsp = await errors.parse_response(await context.session.get(url))
  File "/.venv/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.1:443 ssl:default [Connect call failed ('192.168.0.1', 443)]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.1', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "sidecar.py", line 82, in kopf_thread
    loop.run_until_complete(kopf.operator(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/.venv/lib/python3.8/site-packages/kopf/reactor/running.py", line 118, in operator
    await run_tasks(operator_tasks, ignored=existing_tasks)
  File "/.venv/lib/python3.8/site-packages/kopf/reactor/running.py", line 355, in run_tasks
    await aiotasks.reraise(root_done | root_cancelled | hung_done | hung_cancelled)
  File "/.venv/lib/python3.8/site-packages/kopf/utilities/aiotasks.py", line 199, in reraise
    task.result()  # can raise the regular (non-cancellation) exceptions.
  File "/.venv/lib/python3.8/site-packages/kopf/utilities/aiotasks.py", line 69, in guard
    await coro
  File "/.venv/lib/python3.8/site-packages/kopf/reactor/observation.py", line 104, in resource_observer
    resources = await scanning.scan_resources(groups=group_filter)
  File "/.venv/lib/python3.8/site-packages/kopf/clients/auth.py", line 44, in wrapper
    return await fn(*args, **kwargs, context=context)
  File "/.venv/lib/python3.8/site-packages/kopf/clients/scanning.py", line 22, in scan_resources
    resources.update(await coro)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 619, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/.venv/lib/python3.8/site-packages/kopf/clients/scanning.py", line 59, in _read_new_apis
    rsp = await errors.parse_response(await context.session.get(url))
  File "/.venv/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/.venv/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.1:443 ssl:default [Connect call failed ('192.168.0.1', 443)]
```
This time it was a connection refused error.

**Comment by OmegaVVeapon** [comment]
Will most likely need Nolar's fixes from https://github.com/nolar/kopf/pull/788 for this.

Luckily, it's a difficult condition to reproduce so the urgency isn't as high.
